const constants = {
  hotelBook: 'Hotel Book',
  navExpand: 'xl',
  navColapse: 'justify-content-end',
  authButton: 'Login or SignUp',
  about: 'About',
  aboutCompany: 'About-us',
  termsAndConditions: 'Terms and Conditions',
  company: 'Our Company',
  cardElementBase: '#32325d',
  cardElementFontFamily: '"Helvetica Neue", Helvetica, sans-serif',
  cardElementFontSmoothing: 'antialiased',
  cardElementFontSize: '16px',
  cardElementFontColor: '#aab7c4',
  cardElementInvalidFontColor: '#fa755a',
  cardElementInvalidIconColor: '#fa755a',
  checkOutFormMargin: '35vh auto',
  checkOutFormDisplay: 'flex',
  checkOutFormFlexDirection: 'column',
  checkOutFormAlignContent: 'flex-start',
  checkOutFormDivFlexDirection: 'row',
  checkOutFormDivAlignContent: 'flex-start',
  checkOutFormDivJustifyContent: 'space-between',
  checkOutFormButton: '2em auto 1em',
  checkOutFormLabel: 'Email',
  checkOutFormId: 'outlined-email-input',
  checkOutFormHelperText: `Email you'll recive updates and receipts on`,
  checkOutFormEmailMargin: 'normal',
  checkOutFormVariant: 'outlined',
  emailType: 'email',
  paymentButtonVariant: 'contained',
  paymentButtonColor: 'primary',
  pay: 'Pay',
  subscription: 'Subscription',
  clientSecret: 'client-secret',
  caseIncrease: 'increase',
  caseDecrease: 'decrease',
  anchorVertical: 'bottom',
  anchorHorizontal: 'center',
  transformOriginVertical: 'top',
  rooms: 'Rooms:(max:4)',
  adults: 'Adults:(Age 12+ yr)',
  children: 'Children: (0-12 yr)',
  hotelInfo: 'Hotel Info',
  customCardTypeFilter: 'filter',
  checkInDetail: 'Check-In:',
  checkOutDetail: 'Check-Out:',
  guestDetail: 'Guests:',
  guestInfo: 'Guest Details',
  priceSummary: 'Price Summary',
  payNow: 'Pay Now',
  numberOfGuests: 'Number of Guests:',
  checkBoxTypeCheck: 'check',
  checkBoxTypeRatings: 'ratings',
  freeCancellationName: 'Free Cancellation Available',
  freeCancellationValue: 'Free Cancellation ',
  freeBreakfastName: 'Free Breakfast Available',
  freeBreakFastValue: 'Free Breakfast ',
  hotelRatings: 'Hotel Ratings',
  hotelPrice: 'PriceRange',
  hotelType: 'Hotel Type',
  hotelAmenities: 'Amenities',
  guestsAndRooms: 'Guests and Rooms :',
  buttonSizeLarge: 'large',
  searchHotels: 'Search Hotels',
  navbarBg: 'primary',
  navbarVariant: 'dark',
  navbarClassName: 'mr-auto',
  city: 'City :',
  inputTypeText: 'text',
  updateSearch: 'Update Search',
  updateSearchButtonVariant: 'light',
  customCardTypeCityListing: 'cityListing',
  cititesLabel: 'Cities:',
  nearestLandmark: 'Nearest Landmark:',
  roomEventKey: 'Rooms',
  basePrice: 'Base Price :₹',
  perNight: '/per Night',
  amenitiesEventKey: 'Amenities',
  somePopularAmenities: 'Some of the Popular Amenities provided by the Hotel:',
  tabsId: 'hotelDetails',
  hotelPoliciesEventKey: 'hotelPolicies',
  hotelPoliciesTitle: 'Hotel Policies',
  hotelReviewsEventKey: 'hotelReviews',
  hotelReviewsTitle: 'Hotel Reviews',
  userReviews: 'User Reviews',
  accountIconSizeLarge: 'large',
  selectRoomButtonVariant: 'outline-danger',
  selectRoomButtonSize: 'lg',
  selectRooms: 'Select Rooms',
  roomType: 'Room Type',
  roomOptions: 'Room Options',
  roomInclusions: 'Inclusions',
  roomPrice: 'Price',
  customCardTypeHotelListing: 'hotelListing',
  noHotelsFound: 'No Hotels Found...',
  navbarControls: 'basic-navbar-nav',
  aboutHotelBook: 'About Hotel-Book.com',
  autoCompleteId: 'citySearch',
  autoCompleteLabel: 'Search Location',
  checkBoxColor: 'primary',
  ratingType: 'read-only',
  cardWidth: '18rem',
  imgRounded: 'img-rounded',
  cardVariant: 'top',
  inputTypeDate: 'date',
  guestEmail: 'Email Address :',
  inputTypeEmail: 'email',
  guestNameLabel: 'Guest Name :',
  guestName: 'guestName',
  mobile: 'Mobile :',
  inputTypeNumber: 'number',
  guestMobile: 'mobile',
  proceedToPayment: 'Proceed To Payment',
  buttonTypeSubmit: 'submit',
  login: 'Login',
  userPasswordLabel: 'Password :',
  inputTypePassword: 'password',
  submit: 'Submit',
  notAUser: 'Not a User?',
  signUp: 'Sign-Up',
  userName: 'name',
  userNameLabel: 'Your Name :',
  userAbout: 'about',
  inputTypeTextArea: 'textarea',
  userConfirmPasswordLabel: 'Confirm Password :',
  userConfirmPasswordName: 'confirmPassword',
  userImage: 'image',
  inputTypeFile: 'file',
  user: 'user',
  token: 'token',
  invalidEmail: '*Invalid Email',
  required: '*Required',
  passwordLength: 'Password has to be longer than 5 characters!',
  passwordMatch: 'Passwords much match',
  nameLength: 'Name should be of minimum 6 characters',
  invalidMobile: 'Invalid Mobile number',
  booking: 'booking',
  userLoggedIn: 'User Logged In',
  alertSuccess: 'success',
  bookingSuccess: 'Booking Success',
  alertFailure: 'danger',
  notification: 'notification',
  error: 'Oops! Something went wrong',
};
export default constants;
