const schemaContants = {
  checkOutFormMaxWidth: 500,
  totalRoom: 1,
  totalAduts: 2,
  totalChildren: 0,
  maxAdults: 8,
  minGuestsandRooms: 1,
  maxRooms: 4,
  bookingDetailColSpan: 6,
  bookingDetailColOffset: 1,
  priceInfoColSpan: 3,
  priceInfoColOffset: 1,
  hotelDetailColXs: 7,
  hotelDetailColMd: 5,
  popularAmenitiesColXs: 4,
  popularAmenitiesColMd: 2,
  hotelReviewColSm: 11,
  hotelListingColSpan: 10,
  hotelListingColOffset: 2,
  productFilterCol: 4,
  hotelListingCol: 8,
  AboutPageColSpan: 10,
  AboutPageColOffset: 2,
  userProfileColSpan: 10,
  userProfileColOffset: 2,
  userImageCol: 4,
  userDetailCol: 8,
  minLength: 0,
  minPasswordLength: 5,
  minGuestNameLength: 6,
  minMobileLength: 10,
};
export default schemaContants;
